### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by ArchiDevil** [ArchiDevil/hat#24]
The complete project roadmap is the following list:

- [x] - Proof of concept for processing XLIFF files using TMX with external source (SmartCAT).
- [x] - Store uploaded TMX and XLIFF documents.
- [x] - Make a separate frontend with multiple moving parts.
- [ ] - Use external API for translation of not-found segments (Yandex). This allows to replace other tools which are used with SmartCAT by other translators.
- [ ] - Create profiles for users and list of documents they used and uploaded. Store sensitive data like API keys in the profile.
- [ ] - Make processed XLIFF files editable after processing to fix issues and update some parts.
- [ ] - Create projects system with multiple documents.
- [ ] - Support uploading of new documents from scratch along with already supported XLIFF files. Update TMX files according to these new projects.
- [ ] - Support glossaries.
- [ ] - Support concordance search in project documents.

Other bullets will be added later.
